[general]
debug=2
delay=0.05

[redis]
hostname=localhost
port=6379

[trigger]
; each item listed here will be recorded, the value to the right of the "=" does not matter
; the top row of the Launch Control XL
spectral.channel1.alpha=0

[output]
postfix=diff